all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
- - 27
- - 28
- - 29
- - 30
- - 31
- - 32
- - 33
- - 34
- - 35
- - 36
- - 37
all_joints_names:
- dam_nose
- left_eye
- right_eye
- left_ear
- right_ear
- top_head_dam
- back_1_left
- back_1_right
- back_1_center
- back_2
- back_3
- back_4
- back_5
- back_6
- back_7
- back_8
- back_9
- back_10
- tail_base
- left_armpit
- left_shoulder
- left_wrist
- left_palm
- left_leg_front
- left_leg_behind
- left_ankle
- left_ventrum_side
- right_armpit
- right_shoulder
- right_wrist
- right_palm
- right_leg_front
- right_leg_behind
- right_ankle
- right_ventrum_side
- center_ventrum
- btwn_arms
- btwn_legs
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_dam-single-animalMay26\dam-single-animal_Hannah98shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
global_scale: 0.8
init_weights: snapshot-700000
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_dam-single-animalMay26\Documentation_data-dam-single-animal_98shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 38
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: D:/Hannah/dam-single-animal-Hannah-2022-05-26
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
